### ISSUE TITLE
Suggestion - Better default keyboard controls

### ISSUE THREAD

**Issue by jrugia** [phoboslab/wipeout-rewrite#120]
I find the default controls to be a bit too uncomfortable.  I suggest they're changed as below:

W - Accelerate
A - Left Brake
D - Right Brake
C - Change View
Space Bar - Fire

Feels more natural for me.

If anyone's willing to try it out.  You can edit the source at "/src/wipeout/game.c" - Lines 410-418

>
		[A_UP] = {INPUT_KEY_UP, INPUT_GAMEPAD_DPAD_UP},
		[A_DOWN] = {INPUT_KEY_DOWN, INPUT_GAMEPAD_DPAD_DOWN},
		[A_LEFT] = {INPUT_KEY_LEFT, INPUT_GAMEPAD_DPAD_LEFT},
		[A_RIGHT] = {INPUT_KEY_RIGHT, INPUT_GAMEPAD_DPAD_RIGHT},
		[A_BRAKE_LEFT] = {INPUT_KEY_A, INPUT_GAMEPAD_L_SHOULDER},
		[A_BRAKE_RIGHT] = {INPUT_KEY_D, INPUT_GAMEPAD_R_SHOULDER},
		[A_THRUST] = {INPUT_KEY_W, INPUT_GAMEPAD_A},
		[A_FIRE] = {INPUT_KEY_SPACE, INPUT_GAMEPAD_X},
		[A_CHANGE_VIEW] = {INPUT_KEY_C, INPUT_GAMEPAD_Y},

**Comment by madorian** [comment]
I'm on NixOS and the game is already compiled. Is it possible to override these at run time?

**Comment by phoboslab** [comment]
In the game go to Options -> Controls.

**Comment by madorian** [comment]
@phoboslab Not sure what you mean, cause it just says TODO when I try that.

**Comment by phoboslab** [comment]
Then you have an old version. The controller options have been added a while ago: https://github.com/phoboslab/wipeout-rewrite/commit/b2e3ae80dd3e5f152cdf35bf58473b8d6cef0ef4 - so just recompile or update your package!?

You can also play the current version on the web: https://phoboslab.org/wipegame/

**Comment by madorian** [comment]
Ah, in NixOS, I seem to have Version: 2023-08-13 and the commit you are referring to is 2023-08-15;)
