### ISSUE TITLE
How to convert Music Tracks to QOA format?

### ISSUE THREAD

**Issue by Cp1N3m0** [phoboslab/wipeout-rewrite#126]
Hello,

How to convert Music Tracks to QOA format ?

Thanks

**Comment by glm11-aoc** [comment]
https://github.com/phoboslab/qoa requires a little setup but will do the trick

**Comment by Cp1N3m0** [comment]
> https://github.com/phoboslab/qoa requires a little setup but will do the trick

Thanks
