### ISSUE TITLE
Linking against modern (non-GLX) OpenGL in GNU/Linux

### ISSUE THREAD

**Issue by vanfanel** [phoboslab/wipeout-rewrite#15]
Hi there @phoboslab 

Awesome work you did here! Enjoying this immensely on my GNU/Linux systems.
Other than that, this links against the old/legacy OpenGL GLX implementation here:
https://github.com/phoboslab/wipeout-rewrite/blob/cb2a1eded3f7048f05615b0981b8eb17d7ed23e4/Makefile#L47

On Wayland and KMS/DRM systems, I have to replace `-lGL` with `-lOpenGL`, which links properly against modern OpenGL (which is MESA + GLVND, thus abstracting the windwing system as it should be).

So, what about replacing `-lGL` with `-lOpenGL`? GLX is a thing of the past anyway.

**Comment by phoboslab** [comment]
I'm consolidating all the OpenGL issues and closing this one. Further discussion in #19.

**Comment by vanfanel** [comment]
Fixed in https://github.com/phoboslab/wipeout-rewrite/pull/22
