### ISSUE TITLE
Black screen on Raspberry Pi 4

### ISSUE THREAD

**Issue by vanfanel** [phoboslab/wipeout-rewrite#16]
Hi there again @phoboslab 

I have tried to build this on the Pi4, using latest stable MESA and latest SDL2 git code version.
It builds fine, however I get a black screen upon game start (not even the intro is shown).

The Pi4 supports GLES up to 3.1 and full OpenGL up to 2.1 (appart from Vulkan)

I suspect the game is trying to initialize a full OpenGL 3.x environment, am I right?

I can see you initialize the OpenGL renderer here:
https://github.com/phoboslab/wipeout-rewrite/blob/cb2a1eded3f7048f05615b0981b8eb17d7ed23e4/src/platform_sdl.c#L222
...But I don't see where do you try to pass an OpenGL profile or major/minor version.

In any case, would it be possible to have GLES 3.1 or even GLES 2.1 support?

**Comment by phoboslab** [comment]
The game already uses GLES2 for the Sokol+WASM target, so I guess it is possible.

I'm consolidating all the OpenGL issues and closing this one. Further discussion in #19.

**Comment by vanfanel** [comment]
Fixed in https://github.com/phoboslab/wipeout-rewrite/pull/22
