### ISSUE TITLE
Mac build complaining about undeclared function

### ISSUE THREAD

**Issue by depsypher** [phoboslab/wipeout-rewrite#17]
Very well may be something odd about my particular system (MacOS Ventura 13.5) but I kept getting this until I disabled that error:
```
src/render_gl.c:578:2: error: call to undeclared function 'glFramebufferTexture'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        glFramebufferTexture(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, backbuffer_texture, 0);
```

Not sure if this is the right move (been a long time since I touched anything C related), but I get successful compile with this:
```C_FLAGS ?= -std=gnu99 -Wall -Wno-unused-variable -Wno-implicit-function-declaration```

Happy to see it run after that though! Super cool project.

**Comment by phoboslab** [comment]
I'm consolidating all the OpenGL issues and closing this one. Further discussion in #19.
