### ISSUE TITLE
SDL target fail to render graphics on Debian

### ISSUE THREAD

**Issue by dilworks** [phoboslab/wipeout-rewrite#18]
Hi there, and thanks for the port (seriously, those ports are godsends nowadays)

Sadly I'm having a hard time trying to run them on my Debian boxes. I'm testing at two setups at home:

- A Sandy Bridge i5 (HD3000 IGP) laptop running Debian Bullseye (yeah, I know... I should upgrade Someday™): on that one the SDL target renders a black screen and nothing else (but I can heard the game sounds, and game reacts to keypresses). On that one the sokol target works fine (aside of the obvious lack of gamepad support).

- A even older Core 2 Duo laptop with a MUCH older Radeon X1400 GPU, but this one runs Bookworm: instead of a black screen, on this one the SDL target renders a screen full of static garbage (but again, the rest of the game seems to work). The sokol target does NOT run on this one due to "GLX: failed to create GL context" (most likely because it wants OpenGL 3? This lowly 17 year old R500 can only do 2.0), and dies there.

On both machines I get no errors logged when running the game with the SDL-target binaries, just the normal texture load messages.

**Comment by phoboslab** [comment]
I'm consolidating all the OpenGL issues and closing this one. Further discussion in #19.
