### ISSUE TITLE
Figure out which OpenGL version(s) to use

### ISSUE THREAD

**Issue by phoboslab** [phoboslab/wipeout-rewrite#19]
Related to #15, #16, #17 and #18 - we're currently in a mess of different OpenGL version and support libraries. My understanding of this is quite limited, so I'm not sure how to go forward.

Currently we use OpenGL 2.x (I believe) with SDL, WebGL1 (aka GLES2) on WASM and OpenGL 3.3 on Sokol. Additionally, the sokol_app version currently in the tree is quite outdated. The current sokol_app only supports OpenGL 3.3 and WebGL2 (aka GLES3).

The renderer for wipEout only *needs* OpenGL 2.x, but using that is causing a bunch of problems on different platforms. WebGL1 also forces us to [use a 16bit depth buffer](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/render_gl.c#L58-L75) which is not optimal. So I guess we should bring this all to a sane, up-to-date level that hopefully runs on all modern hardware.

So:
1. what are the current best practices for gl support libraries on each platform? Can we get rid of this [dance](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/render_gl.c#L3-L26) with extensions that's using glext.h on MacOS vs. glew.h on Linux?
2. what are the OpenGL versions we _really_ need to support? From my understanding OpenGL 3.3 and WebGL2 (aka. GLES3) are good targets!?
3. as pointed out in #16, SDL currently doesn't specify the OpenGL version at all - how do we fix this?

I'd like to find a solution that runs on all platforms ((Sokol|SDL)*(Win|Mac|Linux) and Sokol+WASM) and requires minimal `#ifdefs`.

**Comment by vanfanel** [comment]
Hi!

I did a PR here to address this in part (more options can be added on top of my PR I guess, but it works very well as it is):

https://github.com/phoboslab/wipeout-rewrite/pull/22

As noted there, I moved to linking against MESA's modern GLVND by default, and you can specify to use GLX with `USE_GLX=true`

Also, I added the possibility to specify `OPENGL_VERSION=GLES2` so things work on GLES2 platforms.

For example, with this I can do a Pi-compatible version that looks and plays incredibly well at rock-solid 60FPS with vsync on KMS/DRM or Wayland:

`GL_VERSION=GLES2 make sdl -j4`

**Comment by dilworks** [comment]
Just my two (highly devaluated) cents: people are going to try get this running on all sorts of hardware, including... old GPUs (I know, we retroenthusiasts can be... something, yes).

OpenGL 3.3 as a minimum target looks kinda restrictive to me, considering that this game should run fine even on older GPUs - 2.0 looks like a reasonable base target, as it covers a wider group of GPUs. Of course, someone will eventually come with a PR with Vulkan/D3D/swrast/whatever renderers, but OGL2.0 is a nice middle ground for people willing to get involved with this.

**Comment by vanfanel** [comment]
@dilworks I agree with you. But this works on GLES2 already with my PR here: https://github.com/phoboslab/wipeout-rewrite/pull/22
...which means it's really going to run everywhere, from Windows XP with an ancient CPU to latest GNU/Linux distros. It's more compatible than GL2, since it's in fact a GL2 subset for light systems.

**Comment by dilworks** [comment]
@vanfanel your PR actually fixed SDL rendering on Debian for me, now I can actually see things and run the game on my older, OGL2.0-only Radeon, yay~!

**Comment by mrneo240** [comment]
On a fork i have ported it *roughly* to OpenGL 1.2 aka fixed function as a base for porting to older devices.

**Comment by enigma9o7** [comment]
On a different machine with Nvidia 330M, I use the nvidia-340 proprietary driver.  When Makefile changed from -lGL to -lOpenGL it started getting black screen.   I wasn't sure how to specify it so I just changed Makefile itself and then it worked again.  Just FYI, maybe want to add that info to the build instructions in the main readme, unless it can automatic determine which is supposed to work.  I personally don't understand it but I do believe this it coudl be related to this drivers poor EGL support.  Under GLX, it supports desktop GL 3.3.  But under EGL it only has GLES 2.0 and no desktop GL at all, and maybe that's what this option is doing?

**Comment by vanfanel** [comment]
> On a different machine with Nvidia 330M, I use the nvidia-340 proprietary driver. When Makefile changed from -lGL to -lOpenGL it started getting black screen. I wasn't sure how to specify it so I just changed Makefile itself and then it worked again. Just FYI, maybe want to add that info to the build instructions in the main readme, unless it can automatic determine which is supposed to work.
> 
> I personally don't understand it but I do believe this it coudl be related to this old driver's poor EGL support. Under GLX, it supports desktop GL 3.3. But under EGL it only has GLES 2.0 and no desktop GL at all, and maybe that's what this option is doing?
> 
> ```
> $ glxinfo|grep ersion
> server glx version string: 1.4
> client glx version string: 1.4
> GLX version: 1.4
> OpenGL core profile version string: 3.3.0 NVIDIA 340.108
> OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
> OpenGL version string: 3.3.0 NVIDIA 340.108
> OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
> OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.108 340.108
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00
> ```
> 
> [eglinfo.txt](https://github.com/phoboslab/wipeout-rewrite/files/12386684/eglinfo.txt)

For old closed-source NVIDIA driver, you have to do:

`USE_GLX=true  make sdl`

No need to alter the Makefile, it's all ready to build with no problems if you specify that you want to use the legacy GLX implementation.

Old NVIDIA closed-source driver is broken by design and will never support anything beyond legacy GLX.

**Comment by turbolent** [comment]
It looks like the goal of the issue is to modernize the renderer, but would it be possible to add (a) render(s) that require less than OpenGL 2.x, e.g. just 1.3? Would it possible to have a software renderer? That would allow porting the game to other platforms.
