### ISSUE TITLE
Can't seem to start game from (from keyboard)

### ISSUE THREAD

**Issue by stuaxo** [phoboslab/wipeout-rewrite#2]
I can press enter and get to the menu that has "start game" but then it doesn't do anything.

Ubuntu: amd64

**Comment by The-King-of-Toasters** [comment]
Use X to select and C to exit.

**Comment by stuaxo** [comment]
Thanks :)  I was lulled into a false sense of knowing-what-I-was-doing because enter worked on the earlier screen.

**Comment by itsnoteasy** [comment]
> Use X to select and C to exit.

could you upload a full list of keyboard keys and their mappings. I did check the input.c, but wasn't enlightened. it would make it much easier to get a controller working on this end.

**Comment by phoboslab** [comment]
All key bindings are here: https://github.com/phoboslab/wipeout-rewrite/blob/master/src/wipeout/game.c#L508-L573 – this is using the input system to bind keys to specific actions (`A_*`) in the game.

The input system allows for multiple "layers" of key bindings. The idea is that the `SYSTEM` layer is hardcoded in the executable, while the `USER` layer should be configurable through the config file. The `SYSTEM` binds are used in all menus, whereas the `USER` binds are used in the race part. So even if you completely screw up the `USER` binds somehow, you will be able to navigate menus and reconfigure.

Note that the configurability of `USER` binds is not yet implemented. It's missing the options page for that as well as the functionality to store/load these binds from the save.dat.

Inputs that support more than just a digital on/off (e.g. analog sticks, analog triggers) will set actions states to the normalized `0.0 - 1.0` range. This is used for all controls where analog input makes sense: thrust, brakes and steering. See how [A_THRUST](https://github.com/phoboslab/wipeout-rewrite/blob/master/src/wipeout/ship_player.c#L121) is handled for example: the `input_state(A_THRUST)` (in the range `0.0 - 1.0`) is multiplied with the max thrust. For keyboard or other digital buttons the state will be either `0` or `1` but analog inputs allow for a `0.5` state etc.

Also note that gamepad/joystick input is currently only supported with the SDL platform backend.

**Comment by itsnoteasy** [comment]
Thanks for the link. it does away with the guesswork. i didn't wish to imply i was a developer. I have a programmable hitbox that i was trying to setup as a keyboard.

**Comment by stuaxo** [comment]
Having these included in the docs would be be a nice to have.
