### ISSUE TITLE
Crash when trying to get past title screen (wipeout/common/leeg.cmp is missing)

### ISSUE THREAD

**Issue by hazelnot** [phoboslab/wipeout-rewrite#34]
The game crashes when I attempt to get past the title screen by pressing enter.

Apparently `wipeout/common/leeg.cmp` is missing, but the NTSC PSX CD I used doesn't seem to contain that file.

```
load cmp wipeout/common/leeg.cmp
Abort at "src/utils.c" line 23: Could not open file for reading: wipeout/common/leeg.cmp
```

**Comment by mickski56** [comment]
No this port uses a mix of assets from the psx and windows versions. Hint read the Running section of readme.md

**Comment by mickski56** [comment]
That is correct

**Comment by hazelnot** [comment]
It's clearly not correct, since it _requires_ the PC data to run

**Comment by hazelnot** [comment]
Anyway, it worked now, but I strongly suggest rephrasing the readme text 😅
