### ISSUE TITLE
[feature] key shortcut for togling fullscreen

### ISSUE THREAD

**Issue by pirate486743186** [phoboslab/wipeout-rewrite#45]
You are forced to go to the main menu to toggle fullscreen, that's very annoying.

Something like F11

**Comment by Sanyam-jain30** [comment]
Can I please work on this?

**Comment by phoboslab** [comment]
Ha, sorry @Sanyam-jain30; I started on this just 10 mins ago. Bad timing ._.

**Comment by Sanyam-jain30** [comment]
No worries @phoboslab. It is great the issue is now solved
