### ISSUE TITLE
the music can't be played in an external player

### ISSUE THREAD

**Issue by pirate486743186** [phoboslab/wipeout-rewrite#46]
i'm sure the qoa format is fine for games in general... but this also means that the very fine music of this game can't be played in your favorite music player along with the rest of your music....

**Comment by phoboslab** [comment]
You can buy MP3s or FLAC here: https://coldstorage.bandcamp.com/album/slipstream-the-music-from-wipeout

**Comment by phoboslab** [comment]
Not against it, as outlined in my blog post. Awaiting your pull request to support MP3 and/or Vorbis.
