### ISSUE TITLE
[Feature] Would be amazing to implement the game used in the Hackers film 

### ISSUE THREAD

**Issue by johnflan** [phoboslab/wipeout-rewrite#49]
There was a sequence in the Hackers (1995) where a version of Wipeout was used in the game. Would be amazing it that 'level/game' could be recreated.

**Comment by phoboslab** [comment]
There's multiple problems with this

- in Hackers, it wasn't a game, but a pre-rendered video
- it's not clear what exactly the gameplay; what is presented there looks like an incoherent mess
- we currently don't have the tools to master any new tracks and models
- it would be a whole lot of work
- it's really out of scope for this restoration here

Closing this as not planned.
