### ISSUE TITLE
Make keys selectable

### ISSUE THREAD

**Issue by 82MHz** [phoboslab/wipeout-rewrite#6]
First off, amazing project!

One thing I noticed is that break is hard-coded to the key 'z', accelerate is 'x'. Makes sense on an english keyboard because the letters are right next to each other.
On a german keyboard though 'z' and 'y' are switched, so next to 'x' is 'y' (that's because the letter z is much more common in German than y, so it was moved to a more accessible position). So playing a game with 'x' and 'z' as controls is awkward... 

Could you therefore make the keys selectable somehow? 

For reference, here's the german keyboard layout:
https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/German-T2-Keyboard-Prototype-May-2012.jpg/880px-German-T2-Keyboard-Prototype-May-2012.jpg

**Comment by maxterry** [comment]
Controls are no longer working correctly for me after https://github.com/phoboslab/wipeout-rewrite/commit/b2e3ae80dd3e5f152cdf35bf58473b8d6cef0ef4 on macOS.

Now, without a save file, thrust is actually the `v` key (though still showing `x` in the controls menu), pressing `Return` also changes the ship perspective, etc.

Thought there may be an issue here, but this is affecting me without a save file: https://github.com/phoboslab/wipeout-rewrite/blob/master/src/wipeout/game.c#L569

Wondering if maybe ASCII value of chars are used so changes in capitalization had an effect here? https://github.com/phoboslab/wipeout-rewrite/commit/0e3422d345124535296317815d84b6516d782af7

**Comment by phoboslab** [comment]
Did you do a clean re-compile? The makefile doesn't pick up changes to the `.h`; all the keys were shuffled around in this commit.

**Comment by phoboslab** [comment]
Makefile fixed in https://github.com/phoboslab/wipeout-rewrite/commit/8c9ec8871e00a6b9bfd74209a4d2e4fbee5af50d

**Comment by maxterry** [comment]
I had been removing the save file and executable but not the build dir. Cleared those out, pulled the latest and recompiled, and controls are working as expected for me now, thanks!
