### ISSUE TITLE
Query: mem_temp_alloc 8 bytes alignment of size

### ISSUE THREAD

**Issue by sujankh** [phoboslab/wipeout-rewrite#68]
Hi, when looking at the the bump allocator i was assuming the following would modify size to be the next multiple of 8 but looks like it is not.
```
	size = ((size >> 3) + 7) << 3; // allign to 8 bytes
```
https://github.com/phoboslab/wipeout-rewrite/blob/ecf1e635082188d3294e10abb255128204854127/src/mem.c#L49 

Here is what i see when i add some logs
```
size: 16  --> becomes: 72
size: 4224  --> becomes: 4280
```
When user request 16 bytes, do we need to reserve 72 bytes in the temp? We could just reserve 16 bytes right?

**Comment by phoboslab** [comment]
Good catch, thanks!
