### ISSUE TITLE
Audio issues followed by complete loss of audio

### ISSUE THREAD

**Issue by artillect** [phoboslab/wipeout-rewrite#8]
First off, I'd like to thank you for creating this! Wipeout was one of my favorite games when I was a kid.

After trying (and failing) a few championship races, at the beginning of one of the races it played every sound effect in order at a higher pitch (Something like "Mines shockwave rockets 3 2 1 Go") and then it played some INCREDIBLY loud glitchy noises before going silent aside from the sound effects. Then, after another lap, the audio went completely silent and the message "Exception thrown, see javascript console" popped up.

I'm not sure how to reproduce this, but here's [the js console's output](https://gist.github.com/artillect/4c640d14d10c2d2afe18374d82d5f3b9) just in case it contains some useful information. I'm using Microsoft Edge version 115.0.1901.200 on Windows 11

**Comment by phoboslab** [comment]
Ugh, sounds like a buffer overrun with the music decoder. Sorry for that; hope your ears are ok! I'm looking into it.

**Comment by artillect** [comment]
Luckily my ears are just fine, thanks for taking a look into this!

**Comment by phoboslab** [comment]
So that was a stupid bug. When the next randomly chosen track happened to be the current one, the music decoder skipped closing and opening the current file and instead... did nothing. Now it rewinds the track.

Related new todo: random music selection shouldn't play the same track twice.

**Comment by artillect** [comment]
Sounds like the sort of thing I would have run into hahaha, thanks for the quick fix!
