### ISSUE TITLE
make broken on MacOS

### ISSUE THREAD

**Issue by johnflan** [phoboslab/wipeout-rewrite#81]
```-UNAME_O := $(shell uname -o)```

the -o parameter is not supported by the MacOS version of uname

**Comment by dseddah** [comment]
man uname gives
(...)
  -o      This is a synonym for the -s option, for compatibility with other systems.

     -p      Write the type of the machine processor architecture to standard output.  (make(1) uses it to set the MACHINE_ARCH variable.)

     -r      Write the current release level of the operating system to standard output.

     -s      Write the name of the operating system implementation to standard output.
     
     
 uname -v
Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000

located on /usr/bin 


are you sure you're not using a version installed by brew, fink or darwin ports for some reasons ?
