### ISSUE TITLE
build guide

### ISSUE THREAD

**Issue by B-Nerd** [phoboslab/wipeout-rewrite#85]
i wish for a proper build game that tell what version of the game you need with md5 hash, what commands to run & where i need to put the bin & cue file

**Comment by phoboslab** [comment]
It's all in the [Readme](https://github.com/phoboslab/wipeout-rewrite#readme). Binaries will not be provided here. You'll have to compile it yourself.

**Comment by B-Nerd** [comment]
thisis not a build step The Wipeout rewrite supports two different platform-backends: [SDL2](https://github.com/libsdl-org/SDL) and [Sokol](https://github.com/floooh/sokol). The only difference in features is that the SDL2 backend supports game controllers (joysticks, gamepads) and uses OpenGL 2.x, while the Sokol backend does not support controllers and uses OpenGL 3.3. The Sokol backend is also only supported on macOS, Linux, Windows and Emscripten.

For Linux & Unix-likes a simple Makefile is a provided. Additionally, this project can be build with [CMake](https://cmake.org/) for all platforms.

Consult the following sections for how to install the prerequisites for your platform: this is a build guide https://github.com/OpenDriver2/REDRIVER2/wiki/Installation-instructions so you need what commands i need to run what game & game version i need & where the bin & the cue need to go

**Comment by phoboslab** [comment]
> so you need what commands i need to run what game & game version i need & where the bin & the cue need to go & i don't want a binary

See the "Running" section in the Readme.

**Comment by B-Nerd** [comment]
so i don't need to run make because there is a make file but what version of the ntsc wipeout do i need & what command do you need to run after git clone & for the version & i use now driver 1 these are both ntsc version SLUS-01161 / SLUS-01318 & SLUS-01161GH / SLUS-01318GH the readme still does not tell that

**Comment by phoboslab** [comment]
> so i don't need to run make because there is a make file

Wat? `make` uses the `Makefile` to compile the game.

> what version of the ntsc wipeout do i need

To the best of my knowledge there's only one wipEout NTSC version for the PSX

> i use now driver 1

Sorry, what does Driver have to do with wipEout?

> the readme still does not tell that

The readme explains exactly which data you need

> what windows version i need for some files

Any windows version that is supported by SDL2: That is Windows XP and upwards. Mac and Linux works too.


Not sure what you're up to, but I think you might be happier with this other restoration effort: https://github.com/wipeout-phantom-edition/wipeout-phantom-edition

**Comment by B-Nerd** [comment]
what i mend driver tell me that i need a version commands & make is the command you need to run a makefile so tell people that in the readme & i don't have a problem with building from source people need a readme that tell what step you need to build from source so things like git clone, cd & make your blog tell me the windows version needed is Wipeout ATI 3D Rage Edition but can you also tell it in the readme

**Comment by B-Nerd** [comment]
& i don't want to be salty but at least phantom tell me where to bin & cue go & redriver tells me what commands i need to run to use the makefile & not this as the build steps For Linux & Unix-likes a simple Makefile is a provided also this part is not a build step https://github.com/phoboslab/wipeout-rewrite#arch-linux

**Comment by phoboslab** [comment]
No worries. This repository is not in a state where it is a "turnkey solution". It's currently meant for people who want to work on the game and have some experience with C.

> the only thing I'm asking for is build steps & where the wipeout psx files go

From the readme:
> The directory structure is assumed to be as follows
```
./wipegame # the executable
./wipeout/textures/
./wipeout/music/track01.qoa
./wipeout/music/track02.qoa
...
```

> Note that the blog post announcing this project may or may not provide a link to a ZIP containing all files needed. Who knows!

To be clear: this version of the game here **does not** work with CD-images (.bin/.cue/.iso) at all.

**Comment by B-Nerd** [comment]
oke i don't want a zip but maybe when it is out of the testing phase ad a build guide that tell people who are less techy what steps are needed i can get i to run sort off it has problems with the windows files & it looked like i need more these folders because of the ... i only know those for click here to see more
