### ISSUE TITLE
Analog input not detected

### ISSUE THREAD

**Issue by UltraBlackLinux** [phoboslab/wipeout-rewrite#87]
Hey there,
I cannot get the game to detect any of my stick inputs (L or R) during a race, but weirdly it does work in the menus.
I always have to resort back to the arrow keys, and they are much too sensitive for my taste.
I'm using SC-controller as my input backend, which then emulates an xbox gamepad, which games are usually able to use.
Can you fix that?
Thanks!

**Comment by phoboslab** [comment]
Can you please check if it works after a restart of the game? I.e configure the stick in the options, exit and start again.

There's currently a bug where newly bound buttons don't work as expected.

**Comment by UltraBlackLinux** [comment]
no, a restart does not help. I didn't rebind anything, so I don't think it's a rebinding bug.
I'm alsos confused because the settings only show digital input options, but the readme states that analog input is a thing.

**Comment by phoboslab** [comment]
Well, you have to actually bind the stick to up, down, left, right in the options to use them during the game. By default only the DPad of a game controller is bound.

**Comment by UltraBlackLinux** [comment]
ooh that makes sense. I didn't know that. I expected it to work by default since the menus picked it up.

**Comment by phoboslab** [comment]
One of the many things to improve; sorry for the confusion. I will update the Readme to point that out.
