### ISSUE TITLE
an idea for walls

### ISSUE THREAD

**Issue by UltraBlackLinux** [phoboslab/wipeout-rewrite#88]
I suggest making the walls deflect the player ship like mirrors reflect light (in angle = out angle), so it's easier to recover from collisions (the tunnel at the end is brutal...). From my experience it seems that when you collide with a wall once, you probably collide with the wall again, however the slowdown is brutal. Please lower that to maybe 1/4 of that

**Comment by phoboslab** [comment]
Dup of https://github.com/phoboslab/wipeout-rewrite/issues/13

**Comment by UltraBlackLinux** [comment]
I have no idea how the original game behaves in this regard, I haven't played it.
