### ISSUE TITLE
Difference in the way it handle jumps with original game

### ISSUE THREAD

**Issue by tigrouind** [phoboslab/wipeout-rewrite#96]
Please take a look at this video :

https://github.com/phoboslab/wipeout-rewrite/assets/2211721/cad36ba8-a78e-4ec7-b8f8-912c30d225b1

Original: reduced thrust after the jump (despite the fact that I kept pressing the X button)
Rewriting: no reduction in thrust, the ship crashes into the mountain.

**Comment by PoloniumRain** [comment]
I just discovered this rewrite and after playing it in the browser, the jumps immediately stood out as handling wrong (i still play the original PSX version to this day) just as you've shown in your video. It mostly affects the Rapier class. 

The ships are also front heavy in either class, so after a jump the ships nose will start to point downwards into the ground, so you crash. Even a small jump will now cause the ships nose to scrape the floor, where this did not happen before. Pressing back to lift the nose up will slightly help, but not much.

**Comment by phoboslab** [comment]
That took some investigating!

The original game calculates the distance to the nearest track section by largely ignoring the .y component (height) of the ship. This got lost in the rewrite and the `SHIP_FLYING` physics were used even when the ship was directly above the track. Above commit fixes this.
